version: '3'
networks:
  api_server_default:
    external: true
services:
  tb_user:
    restart: unless-stopped
    image: tb/tomato-todo
    network_mode: "host"
    environment:
      CONSUL_IP:
      DATABASE_MONGODB_USERNAME_PASSWORD:
      DATABASE_MONGODB_HOST_PORT:
      REDIS_PORT:
      REDIS_HOST:
      REDIS_PASSWORD:
    ports:
     - "10003:10003"